# Generated by Django 5.0.7 on 2024-08-13 04:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='time',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AddField(
            model_name='hall',
            name='image',
            field=models.URLField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hall',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='number_of_attendees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
