# Generated by Django 5.0.7 on 2024-08-13 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_booking_name_booking_time_hall_image_hall_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='image',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
